### ISSUE TITLE
KeyError 1920

### ISSUE THREAD

**Issue by Kayce001** [neuralchen/ASMAGAN#9]
**using the official command:** python main.py --mode test --cuda 0 --version ASMAfinal  --dataloader_workers 8   --testImgRoot ./bench/ --nodeName localhost --checkpoint 350000 --testScriptsName common_useage --specify_sytle 8 

**then error happened** 
Generator Script Name: Conditional_Generator_asm
11 classes
Finished preprocessing the test dataset, total image number: 25...
/home/ama/anaconda3/envs/ASMA/lib/python3.9/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ama/ASMAGAN/main.py", line 266, in <module>
    tester.test()
  File "/home/ama/ASMAGAN/test_scripts/tester_common_useage.py", line 50, in test
    test_data = TestDataset(test_img,batch_size)
  File "/home/ama/ASMAGAN/data_tools/test_data_loader_resize.py", line 36, in __init__
    transform.append(T.Resize(1088,1920))
  File "/home/ama/anaconda3/envs/ASMA/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 336, in __init__
    interpolation = _interpolation_modes_from_int(interpolation)
  File "/home/ama/anaconda3/envs/ASMA/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 47, in _interpolation_modes_from_int
    return inverse_modes_mapping[i]
KeyError: 1920

**Comment by thibault-assiste-par-ordinateur** [comment]
I think it's not working because you are running python3.9.
You should use a specific python3.6 environment as described
$ conda create -n ASMA python=3.6
$ conda activate ASMA

**Comment by GregOriol** [comment]
Fix available there: https://github.com/neuralchen/ASMAGAN/issues/6#issuecomment-1027833851

> open "ASMAGAN/data_tools/test_data_loader_resize.py"
> at line 36 correct like this
> transform.append(T.Resize((1088,1920)))
